name: update-grammars

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  release-please:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '17.x'
      - run: npm ci
      - run: npm run update-grammars
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'deps(grammars): update grammars'
          title: 'deps(grammars): update grammars'
          branch: bot/update-grammars
          delete-branch: true
          labels: 'dependencies,automerge'
          body: |
            Grammar files automatically updated.
